name: what_the_banana
description: "What The Banana"

publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: ^3.6.0



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Dependency Injection
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.3

  logger: ^2.5.0

  # Navigation
  go_router: ^14.6.2
  json_annotation: ^4.9.0

  flutter_launcher_icons: ^0.14.2

  # display
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.4

  # ads
  google_mobile_ads: ^5.2.0

  # utils
  share_plus: ^10.1.3 # for pixel art image share
  path_provider: ^2.1.5
  flutter_colorpicker: ^1.1.0
  image_picker: ^1.1.2
  crop_your_image: ^2.0.0
  zoom_widget: ^2.0.1
  image:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  very_good_analysis:
  freezed: ^2.5.7

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: PixelFont
      fonts:
        - asset: assets/fonts/dung_geun_mo.otf
    - family: UnkemptBold
      fonts:
        - asset: assets/fonts/unkempt_bold.ttf

flutter_gen:
  colors:
    inputs:
      - assets/color/colors.xml