name: what_the_banana
description: "What The Banana"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Dependency Injection
  flutter_riverpod: ^2.6.1

  logger: ^2.5.0

  # Navigation
  go_router: ^14.6.2
  json_annotation: ^4.9.0

  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.2
  very_good_analysis:

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: PixelFont
      fonts:
        - asset: assets/fonts/dung_geun_mo.otf
    - family: UnkemptBold
      fonts:
        - asset: assets/fonts/unkempt_bold.ttf

flutter_gen:
  colors:
    inputs:
      - assets/color/colors.xml