name: what_the_banana
description: "What The Banana"

publish_to: 'none'

version: 1.0.11+11

environment:
  sdk: ^3.6.0



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Dependency Injection
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.3

  logger: ^2.5.0

  # Navigation
  go_router: ^14.6.2
  json_annotation: ^4.9.0

  flutter_launcher_icons: ^0.14.2

  # display
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.4

  # ads
  google_mobile_ads: ^5.2.0

  # localizations
  easy_localization: ^3.0.7+1

  # firebase
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2

  # utils
  share_plus: ^10.1.3 # for pixel art image share
  path_provider: ^2.1.5
  flutter_colorpicker: ^1.1.0
  image_picker: ^1.1.2
  crop_your_image: ^2.0.0
  zoom_widget: ^2.0.1
  image:
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1

  flutter_dotenv: ^5.2.1

  # donation
  flutter_paypal_payment: ^1.0.8
  pedometer: ^4.0.2
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.3

  # qr maker
  qr_flutter: ^4.1.0
  image_gallery_saver_plus: ^4.0.1

  flutter_fortune_wheel: ^1.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  very_good_analysis:
  freezed: ^2.5.7

  # open source
  flutter_oss_licenses: ^3.0.4

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/update_notes/
    - .env

  fonts:
    - family: PixelFont
      fonts:
        - asset: assets/fonts/dung_geun_mo.otf
    - family: UnkemptBold
      fonts:
        - asset: assets/fonts/unkempt_bold.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf
    - family: Hannah
      fonts:
        - asset: assets/fonts/hannabanana.otf
    - family: ssronet
      fonts:
        - asset: assets/fonts/ssronet.otf

flutter_gen:
  colors:
    inputs:
      - assets/color/colors.xml